Fix editable override comparator
punkave/apostrophe-override-options pull request #11
Opened 2017-11-24 14:24 UTC by ETLaurent

Keep the comparator when performing an editable override.

2017-11-28 15:01 UTC, boutell requested changes

2017-11-28 15:01 UTC, boutell commented on index.js
> +        comparator = field.comparator
comparator is an undefined variable. This needs to be fixed. Also use semicolons consistently here and in all statements.

2017-11-28 15:08 UTC, ETLaurent commented on index.js
> +        comparator = field.comparator
Ok. What about `verb` though?

2020-05-12 19:47 UTC, boutell approved these changes

2020-05-12 19:49 UTC, merged