Add merge option
punkave/apostrophe-override-options pull request #12
Opened 2017-11-27 18:28 UTC by ETLaurent

Include `Fix editable override comparator` (https://github.com/punkave/apostrophe-override-options/pull/11/)

2017-11-27 19:27 UTC, ETLaurent commented
Semicolons added!

2017-11-28 15:00 UTC, boutell requested changes
Please use semicolons consistently at the end of statements, otherwise good to go. Thanks.

2017-11-28 15:00 UTC, boutell commented on index.js
> +            })
Please use semicolons consistently at the end of statements here and elsewhere. Otherwise good to go.

2017-11-28 15:21 UTC, merged

2017-11-28 15:21 UTC, boutell commented
Thanks, merged.